cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #442928
selection_background  #e7bdba
url_color             #ffb3af

color0   #131313
color1   #ff7372
color2   #9aff7f
color3   #ffe472
color4   #f29b97
color5   #763532
color6   #ffb3af
color7   #fff0ef
color8   #a59999
color9   #ff9f9f
color10  #b8ffa5
color11  #ffeda5
color12  #ffbebb
color13  #ffc9c7
color14  #ffdcdb
color15  #fff8f8
