# Font Configuration
font_family JetBrains Maple Mono 
font_size 12.0
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

# Window Configuration
window_padding_width 12
background_opacity 0.8
background_blur 32
hide_window_decorations yes
enable_audio_bell no
confirm_os_window_close 0

# Cursor Configuration
cursor_shape beam
cursor_blink_interval 1
cursor_stop_blinking_after 15.0
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# Scrollback
scrollback_lines 3000

# Terminal features
copy_on_select yes
strip_trailing_spaces smart
editor nvim

# Tab configuration
tab_bar_style powerline
tab_bar_align left
map alt+t new_tab_with_cwd
map alt+w close_tab
map ctrl+shift+alt+x close_other_tabs_in_os_window
map alt+] next_tab
map alt+[ previous_tab
map ctrl+shift+alt+\ select_tab
map alt+0 set_tab_title
map ctrl+alt+] move_tab_forward
map ctrl+alt+[ move_tab_backward

# Pane
map alt+\ new_window_with_cwd
map alt+w close_window
map ctrl+alt+j next_window
map ctrl+alt+k previous_window

# Shell integration
shell_integration enabled

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down
map alt+u scroll_line_up
map alt+n scroll_line_down

# URL Hints
map ctrl+shift+u open_url_with_hints
map ctrl+shift+p kitten hints --type path --program "launch --type=overlay nvim"
map ctrl+shift+l kitten hints --type linenum --linenum-action=window nvim +{line} {path}

# Dank color generation
include dank-tabs.conf
include dank-theme.conf
